[package]
name = "dwmdumper"
version = "0.5.0"
edition = "2021"

[dependencies]
processdumper = { path = "processdumper" }

[dependencies.windows]
version = "0.35.0"
features = [
    "alloc",
    "Win32_Foundation",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_UI_WindowsAndMessaging",
]
